# Generated by Django 2.2.24 on 2021-10-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211023_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('P', 'In progress'), ('D', 'Done')], default='C', max_length=30),
        ),
    ]
